# 依赖镜像名称和ID
FROM yiluxiangbei/centos7-openjdk8:latest
# 指定镜像创建者信息
LABEL maintainer="Peter Zhang <zhangchunsheng423@gmail.com>"

WORKDIR /home/bigdata/datax

ADD datax.tar.gz /home/bigdata/

ENV DATAX_HOME /home/bigdata/datax