version: "2"

services:
  namenode:
    image: singularities/hadoop
    command: start-hadoop namenode
    environment:
      HDFS_USER: hdfsuser
    volumes:
      - "./data/hdfs:/opt/hdfs"
    network_mode: "host"

  datanode:
    image: singularities/hadoop
    command: start-hadoop datanode 192.168.0.97
    environment:
      HDFS_USER: hdfsuser
    volumes:
      - "./data/hdfs:/opt/hdfs"
    network_mode: "host"