version: '3'
services:

  neo4jv3:
    image: neo4j:3.4.0 # 3.5.5
    volumes:
      - ./conf:/var/lib/neo4j/conf
      - ./mnt:/var/lib/neo4j/import
      - ./plugins:/plugins
      - ./data:/data
      - ./logs:/var/lib/neo4j/logs
    restart: always
    # privileged: true
    ports:
      - 7470:7474
      - 7680:7687
    networks:
      - condor
    environment:
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_AUTH=neo4j/123456  #修改默认用户密码

networks:
  condor:
    external: true